# MaxFlow ICLR 2026 Submission: Trilogy Visualization Script
# High-Fidelity Rendering: Native vs. Golden Key (v69.5) vs. Master Key (v70.0)

# 1. Load data
load 3PBL.pdb, protein
load 3PBL.pdb, native
remove native and not hetatm

# Note: These files are generated by the benchmark suite
load output_3PBL_Helix-Flow_Muon.pdb, master_key

# 2. General Style
hide everything
show cartoon, protein
set cartoon_transparency, 0.4
color lightblue, protein

show surface, protein
set transparency, 0.7
set surface_color, gray80

# 3. Style Native
show sticks, native
color gray40, native
set stick_size, 0.2
set stick_transparency, 0.5

# 4. Style Master Key (The Winner)
show sticks, master_key
color magenta, master_key
set stick_size, 0.4
util.cbay master_key

# 5. Pocket Environment
select pocket, protein within 5.0 of master_key
show lines, pocket
color gray60, pocket

# 6. Publication Rendering
zoom master_key, 12
bg_color white
set ray_opaque_background, on
set antialias, 2
set ray_trace_mode, 1
set ray_shadow, on

print "MaxFlow ICLR 2026: Visualization Ready."
